language: rust
cache: cargo
rust:
  - stable
  # - beta
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  cargo fmt -- --check &&
  cargo clippy -- -D warnings &&
  cargo test &&
  cargo bench &&
  cargo doc
branches:
  only:
    - master
dist: xenial
